"""Filesystem-backed project store.

Each project lives in `server/projects/<id>/` with this layout:

  state.json       - ProjectState (status, refs to artifacts)
  source.<ext>     - the originally uploaded video
  source.mp4       - normalized H.264 copy used by the pipeline
  transcript.json  - Whisper word-level transcript
  cuts.json        - silence-cut decision list
  cut.mp4          - silence-cut intermediate
  graded.mp4       - LUT-applied intermediate
  brand.json       - BrandBook
  lut.cube         - uploaded LUT (optional)
  composition/     - generated Hyperframes project
  exports/         - rendered MP4 outputs
"""

from __future__ import annotations

import json
import os
import secrets
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

ROOT = Path(__file__).resolve().parent
# Allow overriding via env so volumes mount cleanly on Railway / Fly / etc.
PROJECTS_DIR = Path(os.environ.get("HFVP_PROJECTS_DIR") or (ROOT / "projects"))
PROJECTS_DIR.mkdir(parents=True, exist_ok=True)


class Stage(BaseModel):
    name: str
    status: str = "pending"  # pending | running | done | error
    message: str | None = None
    started_at: str | None = None
    finished_at: str | None = None


class ProjectState(BaseModel):
    id: str
    name: str
    created_at: str = Field(default_factory=lambda: _now())
    updated_at: str = Field(default_factory=lambda: _now())
    source_filename: str | None = None
    source_duration: float | None = None
    # Media-source mode: "uploaded" (file copied into pdir/source.mp4) or
    # "external" (referenced in place from the user's disk; pdir/source.mp4
    # is a 720p proxy generated by services/proxy.py, and the original is
    # at source_external_path). Old projects default to "uploaded" so the
    # field can be added without migration.
    source_kind: str = "uploaded"
    source_external_path: str | None = None
    has_transcript: bool = False
    has_cuts: bool = False
    has_lut: bool = False
    lut_filename: str | None = None
    has_brand: bool = False
    has_render: bool = False
    last_export: str | None = None
    angles: list[dict[str, Any]] = Field(default_factory=list)  # [{name, filename, duration, tags?}, ...]
    mode: str = "single"  # legacy single | vlog | podcast — kept for compat
    # Project type the user picked at creation. Drives which sections of
    # the UI appear (sidebar filter). Frozen for the project unless the
    # user explicitly changes via the topbar pill.
    kind: str = "podcast"  # "podcast" | "multicam_podcast" | "reels" | "vlog" | "general"
    clips: list[dict[str, Any]] = Field(default_factory=list)  # [{id, name, filename, duration, has_transcript, summary?}, ...]
    music_suggestion: dict[str, Any] | None = None
    music_track: dict[str, Any] | None = None
    has_fillers: bool = False
    fillers_count: int = 0
    has_soundbites: bool = False
    has_story: bool = False
    has_roughcut: bool = False
    has_camera_plan: bool = False
    has_speakers: bool = False
    has_chapters: bool = False
    # Camera color profile of the source footage. When non-rec709, the
    # FCPXML export tags assets so the editor knows which Camera LUT to
    # apply in Final Cut.
    source_color_profile: str = "rec709"  # rec709 | slog3 | clog3 | vlog | applelog | logc | custom
    color_profile_locked: bool = False    # user picked manually — don't auto-detect on next upload
    stages: dict[str, Stage] = Field(default_factory=dict)

    def stage(self, name: str) -> Stage:
        if name not in self.stages:
            self.stages[name] = Stage(name=name)
        return self.stages[name]


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def new_project_id() -> str:
    return f"p_{int(time.time())}_{secrets.token_hex(3)}"


def project_dir(project_id: str) -> Path:
    return PROJECTS_DIR / project_id


def state_path(project_id: str) -> Path:
    return project_dir(project_id) / "state.json"


def load(project_id: str) -> ProjectState:
    p = state_path(project_id)
    if not p.exists():
        raise FileNotFoundError(project_id)
    return ProjectState.model_validate_json(p.read_text())


def save(state: ProjectState) -> None:
    state.updated_at = _now()
    state_path(state.id).write_text(state.model_dump_json(indent=2))


def create(name: str) -> ProjectState:
    pid = new_project_id()
    project_dir(pid).mkdir(parents=True, exist_ok=True)
    (project_dir(pid) / "exports").mkdir(exist_ok=True)
    state = ProjectState(id=pid, name=name or pid)
    save(state)
    return state


def list_projects() -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for child in sorted(PROJECTS_DIR.iterdir(), reverse=True):
        sp = child / "state.json"
        if sp.exists():
            try:
                s = ProjectState.model_validate_json(sp.read_text())
                out.append(
                    {
                        "id": s.id,
                        "name": s.name,
                        "updated_at": s.updated_at,
                        "has_render": s.has_render,
                    }
                )
            except Exception:
                continue
    return out


def write_json(project_id: str, name: str, data: Any) -> Path:
    p = project_dir(project_id) / name
    p.write_text(json.dumps(data, ensure_ascii=False, indent=2))
    return p


def read_json(project_id: str, name: str) -> Any:
    p = project_dir(project_id) / name
    return json.loads(p.read_text())


# ---- snapshots ---------------------------------------------------------------

SNAPSHOT_FILES = (
    "cuts.json",
    "fillers.json",
    "soundbites.json",
    "story.json",
    "roughcut.json",
    "brand.json",
    "broll_placement.json",
    "speakers.json",
    "social_copy.json",
    "music_suggestion.json",
)


def list_snapshots(project_id: str) -> list[dict[str, Any]]:
    snap_dir = project_dir(project_id) / "snapshots"
    if not snap_dir.exists():
        return []
    out = []
    for child in sorted(snap_dir.iterdir()):
        if not child.is_dir():
            continue
        meta_path = child / "meta.json"
        if meta_path.exists():
            out.append(json.loads(meta_path.read_text()))
    return out


def take_snapshot(project_id: str, label: str) -> dict[str, Any]:
    snap_dir = project_dir(project_id) / "snapshots"
    snap_dir.mkdir(exist_ok=True)
    snap_id = f"snap_{int(time.time())}_{secrets.token_hex(2)}"
    out = snap_dir / snap_id
    out.mkdir()
    state = load(project_id)
    captured: list[str] = []
    for name in SNAPSHOT_FILES:
        src = project_dir(project_id) / name
        if src.exists():
            (out / name).write_text(src.read_text())
            captured.append(name)
    meta = {
        "id": snap_id,
        "label": label or snap_id,
        "created_at": _now(),
        "captured_files": captured,
        "fillers_count": state.fillers_count,
        "has_cuts": state.has_cuts,
        "has_soundbites": state.has_soundbites,
        "has_story": state.has_story,
        "has_roughcut": state.has_roughcut,
    }
    (out / "meta.json").write_text(json.dumps(meta, indent=2))
    return meta


def append_render_history(
    project_id: str,
    *,
    name: str,
    kind: str,
    url: str,
    bytes: int,
    extra: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Track every export that produces a downloadable artifact."""
    p = project_dir(project_id) / "history.json"
    entries: list[dict[str, Any]] = []
    if p.exists():
        try:
            entries = json.loads(p.read_text())
        except Exception:
            entries = []
    entry = {
        "name": name,
        "kind": kind,
        "url": url,
        "bytes": bytes,
        "ts": _now(),
    }
    if extra:
        entry.update({k: v for k, v in extra.items() if k not in entry})
    entries.append(entry)
    # cap history to 200 most recent
    if len(entries) > 200:
        entries = entries[-200:]
    p.write_text(json.dumps(entries, indent=2, ensure_ascii=False))
    return entry


def get_render_history(project_id: str) -> list[dict[str, Any]]:
    p = project_dir(project_id) / "history.json"
    if not p.exists():
        return []
    try:
        return json.loads(p.read_text())
    except Exception:
        return []


def restore_snapshot(project_id: str, snap_id: str) -> dict[str, Any]:
    snap_dir = project_dir(project_id) / "snapshots" / snap_id
    if not snap_dir.exists():
        raise FileNotFoundError(snap_id)
    restored: list[str] = []
    for name in SNAPSHOT_FILES:
        src = snap_dir / name
        if src.exists():
            (project_dir(project_id) / name).write_text(src.read_text())
            restored.append(name)
    state = load(project_id)
    refresh_artifact_flags(state)
    save(state)
    return {"id": snap_id, "restored_files": restored}


def refresh_artifact_flags(state: ProjectState) -> None:
    """Re-sync the `has_*` boolean flags from the filesystem.

    Called after operations that produce/remove artifacts so the UI sees
    them without each route having to remember to flip the flag.
    """
    pdir = project_dir(state.id)
    state.has_cuts = (pdir / "cuts.json").exists()
    state.has_fillers = (pdir / "fillers.json").exists()
    state.has_soundbites = (pdir / "soundbites.json").exists()
    state.has_story = (pdir / "story.json").exists()
    state.has_roughcut = (pdir / "roughcut.json").exists()
    state.has_brand = (pdir / "brand.json").exists()
    state.has_camera_plan = (pdir / "camera_plan.json").exists()
    state.has_speakers = (pdir / "speakers.json").exists()
    state.has_chapters = (pdir / "chapters.json").exists()
