"""Minimal HTML/CSS sanitizer for LLM-generated overlay cards.

Used by reels_animations: when a hook_card or cta_end animation carries
a `custom_html` field (free-form HTML generated by Claude from a user's
style prompt), we don't trust it. The composition runs in the user's
own browser when previewed inline, so a malicious snippet could touch
localStorage, fire network requests, or pull a remote script.

Strategy:
- Whitelist tags and attributes; drop everything else.
- Strip `<script>` blocks entirely, including their text content.
- No event handlers (`on*` attributes).
- URLs in `src`/`href` must be relative, fragment, or data: — no
  `javascript:`, no remote URLs.
- The output HTML and CSS get auto-scoped to a container ID before
  the composer injects them, so a `body { ... }` rule from the LLM
  can't restyle the rest of the composition.

Stdlib-only — no `bleach`, no `beautifulsoup4` to add to requirements.
"""

from __future__ import annotations

import html as _html
import re
from html.parser import HTMLParser

# Tags safe to render inside an absolutely-positioned card. Notably
# excludes anything that can navigate, run code, or pull resources:
# script, iframe, object, embed, link, meta, form, input, button.
_ALLOWED_TAGS: set[str] = {
    "div", "span", "p", "br", "hr",
    "h1", "h2", "h3", "h4", "h5", "h6",
    "strong", "b", "em", "i", "u", "s", "mark", "small", "sub", "sup",
    "ul", "ol", "li", "blockquote",
    "img",
    # SVG subset — pure decoration; no foreignObject which can host HTML.
    "svg", "g", "path", "circle", "ellipse", "rect", "line", "polyline",
    "polygon", "text", "tspan", "defs", "linearGradient", "radialGradient",
    "stop", "filter", "feGaussianBlur", "feOffset", "feColorMatrix",
    "feMerge", "feMergeNode", "feFlood", "feComposite", "feMorphology",
    "feTurbulence", "feDisplacementMap", "mask", "clipPath", "use",
    "pattern",
}
_SELF_CLOSING: set[str] = {"br", "hr", "img", "path", "circle", "ellipse",
                           "rect", "line", "polyline", "polygon", "stop",
                           "use"}
_ALLOWED_ATTRS: set[str] = {
    "class", "id", "style", "title", "alt", "role",
    # img
    "src", "width", "height",
    # svg
    "viewBox", "viewbox", "xmlns", "fill", "stroke", "stroke-width",
    "stroke-linecap", "stroke-linejoin", "stroke-dasharray", "opacity",
    "d", "cx", "cy", "r", "rx", "ry", "x", "y", "x1", "y1", "x2", "y2",
    "points", "transform", "preserveAspectRatio", "preserveaspectratio",
    "offset", "stop-color", "stop-opacity", "gradientUnits", "gradientunits",
    "gradientTransform", "gradienttransform", "xlink:href", "href",
    "in", "in2", "result", "stdDeviation", "stddeviation", "dx", "dy",
    "values", "type", "operator", "k1", "k2", "k3", "k4",
    "baseFrequency", "basefrequency", "numOctaves", "numoctaves",
    "scale", "filterUnits", "filterunits", "primitiveUnits", "primitiveunits",
    "mode", "flood-color", "flood-opacity",
    # text
    "text-anchor", "dominant-baseline", "font-size", "font-family",
    "font-weight", "letter-spacing",
    # mask / clip
    "mask", "clip-path", "mask-type",
    "patternUnits", "patternunits", "patternContentUnits", "patterncontentunits",
}
# data-* attributes are blanket-allowed via prefix check below — no
# semantic risk since the composer doesn't run user data-* through any
# evaluator.

_BAD_URL_SCHEMES = re.compile(r"^\s*(javascript|vbscript|file)\s*:", re.IGNORECASE)

# CSS chunks we drop wholesale to prevent navigation / scripting / data
# exfiltration via @import or url(http...). `url(data:...)` is fine
# (inline SVG / base64 image).
_CSS_BAD_AT_RULE = re.compile(r"@(import|charset|namespace|font-face)[^;{]*;?", re.IGNORECASE)
_CSS_BAD_URL = re.compile(r"url\s*\(\s*['\"]?\s*(?!data:)(?:https?:|//|file:|javascript:)[^)]*\)", re.IGNORECASE)
_CSS_BAD_EXPRESSION = re.compile(r"expression\s*\(", re.IGNORECASE)
_CSS_BAD_BEHAVIOR = re.compile(r"\bbehavior\s*:", re.IGNORECASE)


def _safe_url(value: str) -> str | None:
    """Return the URL if it's safe, else None.

    Safe = empty, fragment (#anchor), relative (./, ../, /path or path),
    or data: URI. Reject anything with javascript:/vbscript:/file: or
    external http(s).
    """
    if not value:
        return None
    v = value.strip()
    if not v:
        return None
    if _BAD_URL_SCHEMES.match(v):
        return None
    if v.startswith(("data:image/", "#", "/", "./", "../")):
        return v
    # Disallow remote URLs — composition assets must be project-local
    # to be sandbox-safe. (The LLM doesn't have project asset paths
    # anyway; if it produces a src, almost certainly it's bogus.)
    if re.match(r"^[a-z]+://", v, re.IGNORECASE):
        return None
    # Relative path with no scheme — allow.
    return v


class _Sanitizer(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=False)
        self.out: list[str] = []
        # Skip everything inside dropped containers (esp. <script>, <style>
        # which we handle separately, and any disallowed tag's contents).
        self._skip_depth = 0

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        tag_l = tag.lower()
        if tag_l == "script" or tag_l == "style":
            self._skip_depth += 1
            return
        if self._skip_depth:
            self._skip_depth += 1
            return
        if tag_l not in _ALLOWED_TAGS:
            self._skip_depth += 1
            return
        cleaned = self._clean_attrs(tag_l, attrs)
        self.out.append(f"<{tag_l}{cleaned}>")

    def handle_endtag(self, tag: str) -> None:
        tag_l = tag.lower()
        if self._skip_depth:
            self._skip_depth -= 1
            return
        if tag_l not in _ALLOWED_TAGS:
            return
        self.out.append(f"</{tag_l}>")

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        tag_l = tag.lower()
        if self._skip_depth:
            return
        if tag_l not in _ALLOWED_TAGS:
            return
        cleaned = self._clean_attrs(tag_l, attrs)
        slash = " /" if tag_l in _SELF_CLOSING else ""
        self.out.append(f"<{tag_l}{cleaned}{slash}>")

    def handle_data(self, data: str) -> None:
        if self._skip_depth:
            return
        self.out.append(_html.escape(data, quote=False))

    def handle_entityref(self, name: str) -> None:
        if self._skip_depth:
            return
        self.out.append(f"&{name};")

    def handle_charref(self, name: str) -> None:
        if self._skip_depth:
            return
        self.out.append(f"&#{name};")

    def handle_comment(self, data: str) -> None:
        # Drop all comments — they can carry CDATA tricks.
        return

    def _clean_attrs(self, tag: str, attrs: list[tuple[str, str | None]]) -> str:
        kept: list[str] = []
        for name, value in attrs:
            if not name:
                continue
            n = name.lower()
            if n.startswith("on"):                       # event handlers
                continue
            if n == "xmlns:xlink":
                continue
            is_data = n.startswith("data-")
            if not is_data and n not in _ALLOWED_ATTRS:
                continue
            if value is None:
                kept.append(n)
                continue
            v = value
            # URL-bearing attributes
            if n in ("src", "href", "xlink:href"):
                safe = _safe_url(v)
                if safe is None:
                    continue
                v = safe
            # Inline style: strip dangerous chunks, escape quote chars
            if n == "style":
                v = _sanitize_inline_style(v)
                if not v:
                    continue
            # Escape attribute value for HTML insertion
            v_escaped = _html.escape(v, quote=True)
            kept.append(f'{n}="{v_escaped}"')
        return (" " + " ".join(kept)) if kept else ""


def _sanitize_inline_style(value: str) -> str:
    """Drop CSS expressions, javascript:url, behavior: and remote url()."""
    v = _CSS_BAD_EXPRESSION.sub("", value)
    v = _CSS_BAD_BEHAVIOR.sub("", v)
    v = _CSS_BAD_URL.sub("url(about:blank)", v)
    return v.strip()


def sanitize_html(raw: str, *, max_chars: int = 4000) -> str:
    """Sanitize an LLM-emitted HTML fragment for safe injection."""
    if not raw:
        return ""
    if len(raw) > max_chars:
        raw = raw[:max_chars]
    p = _Sanitizer()
    try:
        p.feed(raw)
        p.close()
    except Exception:
        return ""
    return "".join(p.out).strip()


def sanitize_css(raw: str, *, max_chars: int = 1500) -> str:
    """Sanitize a CSS chunk: drop @import/@font-face/etc, remote url(),
    expression(), and behavior:. Returns the cleaned text. The CALLER
    is expected to auto-scope this CSS (prefix selectors with the
    container ID) before injecting it into the document."""
    if not raw:
        return ""
    if len(raw) > max_chars:
        raw = raw[:max_chars]
    v = _CSS_BAD_AT_RULE.sub("", raw)
    v = _CSS_BAD_EXPRESSION.sub("", v)
    v = _CSS_BAD_BEHAVIOR.sub("", v)
    v = _CSS_BAD_URL.sub("url(about:blank)", v)
    # Drop </ to prevent breaking out of a <style> block
    v = v.replace("</", "")
    return v.strip()


# A naive but effective scoper: every selector outside @media/@keyframes
# gets prefixed with the parent ID, so the LLM's CSS can't restyle the
# rest of the document. Inside @keyframes we leave selectors alone
# (those are frame names like `from`, `to`, `50%`, not real selectors).
_AT_BLOCK_RE = re.compile(r"@(keyframes|-webkit-keyframes|-moz-keyframes|supports|media)[^{]*\{")


def scope_css(css: str, parent_id: str) -> str:
    """Prefix every selector in `css` with `#<parent_id>`. Skips selectors
    inside @keyframes (those are frame stops, not selectors)."""
    if not css.strip():
        return ""
    prefix = f"#{parent_id}"
    out: list[str] = []
    i = 0
    n = len(css)
    while i < n:
        # Skip leading whitespace so the @rule regex matches even mid-stream.
        while i < n and css[i] in " \t\r\n":
            out.append(css[i])
            i += 1
        if i >= n:
            break
        # @keyframes / @media / @supports — copy intact (recurse for @media).
        m = _AT_BLOCK_RE.match(css, i)
        if m:
            at_kind = m.group(1).lower()
            block_start = m.end()
            depth = 1
            j = block_start
            while j < n and depth:
                ch = css[j]
                if ch == "{":
                    depth += 1
                elif ch == "}":
                    depth -= 1
                j += 1
            block = css[block_start:j - 1]
            if "media" in at_kind or "supports" in at_kind:
                # Recurse into @media so its rules also get scoped.
                inner_scoped = scope_css(block, parent_id)
                out.append(css[i:block_start] + inner_scoped + "}")
            else:
                # @keyframes — copy raw; selectors inside aren't real selectors.
                out.append(css[i:j])
            i = j
            continue
        # Find next `{` to identify a selector group.
        brace = css.find("{", i)
        if brace == -1:
            out.append(css[i:])
            break
        selector = css[i:brace].strip()
        # Find matching `}` for this block.
        depth = 1
        j = brace + 1
        while j < n and depth:
            ch = css[j]
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
            j += 1
        body = css[brace + 1:j - 1]
        if not selector:
            i = j
            continue
        # Prefix each comma-separated selector with the parent ID.
        parts = [s.strip() for s in selector.split(",") if s.strip()]
        scoped = ", ".join(f"{prefix} {s}" if not s.startswith(prefix) else s for s in parts)
        out.append(f"{scoped} {{{body}}}")
        i = j
    return "".join(out)
